#!/usr/bin/env python3
"""Write the persona-judge reviewer's agent file for each harness from skill/reviewer.md.

reviewer.md is the one source of the reviewer's text. This script writes, under the output folder:

  plugin/agents/persona-judge-reviewer.md                  the Claude Code plugin agent
  plugin/harness-agents/gemini/agents/persona-judge-reviewer.md
                                                           the Gemini CLI agent, in the persona-judge extension
  plugin/harness-agents/codex/persona-judge-reviewer.toml  the Codex agent

Each file carries reviewer.md's body unchanged. The Claude Code agent keeps reviewer.md's name, description and
tools and has no hooks field: Claude Code ignores a plugin agent's hooks, so the guard is wired in
plugin/hooks/hooks.json. The Gemini CLI agent lists Gemini's read, list, search and shell tools and nothing that
writes. The Codex agent runs with sandbox_mode = "read-only". The Gemini CLI and Codex files sit outside
plugin/agents/, because Claude Code loads every file in a plugin's agents folder, subfolders included.

Run it again after every change to reviewer.md; the tests fail when a committed file differs from a fresh run.

Usage: make_agents.py [--out DIR]
  --out DIR   the folder to write into; by default the persona-judge folder this script sits in.

Exit codes: 0 written; 2 a usage error or a reviewer.md this script cannot read.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = "skill/reviewer.md"
NOTICE = f"Generated by tools/make_agents.py from {SOURCE}; edit that file and run the script again."
GEMINI_TOOLS = ["read_file", "read_many_files", "list_directory", "glob", "grep_search", "run_shell_command"]
OUTPUTS = {
    "claude": Path("plugin/agents/persona-judge-reviewer.md"),
    "gemini": Path("plugin/harness-agents/gemini/agents/persona-judge-reviewer.md"),
    "codex": Path("plugin/harness-agents/codex/persona-judge-reviewer.toml"),
}


def read_reviewer(path):
    """Return ({key: raw front matter line}, body) from reviewer.md."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n") or text.count("---\n") < 2:
        raise ValueError(f"{path} has no front matter")
    _, front, body = text.split("---\n", 2)
    lines = {}
    for line in front.splitlines():
        key, sep, _ = line.partition(":")
        if sep and not line.startswith((" ", "#")):
            lines[key] = line
    for key in ("name", "description", "tools"):
        if key not in lines:
            raise ValueError(f"{path} has no {key} in its front matter")
    return lines, body


def value(line):
    return line.split(":", 1)[1].strip()


def claude_agent(lines, body):
    return "\n".join(["---", f"# {NOTICE}", lines["name"], lines["description"], lines["tools"], "---", ""]) + body


def gemini_agent(lines, body):
    tools = "tools: [" + ", ".join(GEMINI_TOOLS) + "]"
    return "\n".join(["---", f"# {NOTICE}", lines["name"], lines["description"], tools, "---", ""]) + body


def codex_agent(lines, body):
    # A TOML multi-line literal string keeps the body exactly: no escapes, and the newline after ''' is dropped.
    if "'''" in body:
        raise ValueError("reviewer.md's body holds ''', which a TOML literal string cannot")
    return "\n".join([
        f"# {NOTICE}",
        f"name = {json.dumps(value(lines['name']), ensure_ascii=False)}",
        f"description = {json.dumps(value(lines['description']), ensure_ascii=False)}",
        'sandbox_mode = "read-only"',
        "developer_instructions = '''",
    ]) + "\n" + body + "'''\n"


def main(argv):
    args = argv[1:]
    if args in (["--help"], ["-h"]):
        print(__doc__.strip())
        return 0
    out = ROOT
    if args:
        if len(args) != 2 or args[0] != "--out":
            print("usage: make_agents.py [--out DIR]", file=sys.stderr)
            return 2
        out = Path(args[1])
    try:
        lines, body = read_reviewer(ROOT / SOURCE)
        texts = {
            "claude": claude_agent(lines, body),
            "gemini": gemini_agent(lines, body),
            "codex": codex_agent(lines, body),
        }
    except (OSError, ValueError) as err:
        print(f"make_agents.py: {err}", file=sys.stderr)
        return 2
    for harness, rel in OUTPUTS.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(texts[harness], encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
